### ISSUE TITLE
'Sources not found or don't support the ddc version: vim-lsp'

### ISSUE THREAD

**Issue by nathandcornell** [shun/ddc-source-vim-lsp#17]
It looks like this plugin is no longer compatible with the latest version of ddc.

An error appears in the bottom bar several times per session:
`[ddc] Sources not found or don't support the ddc version: vim-lsp`

**Comment by Shougo** [comment]
Hm..   apiVersion seems too old.

**Comment by Shougo** [comment]
Please test #18 instead.

**Comment by nathandcornell** [comment]
This was actually my mistake, I did not install the plugin properly.

Updating the docs and ddc version is still probably a good idea, though. 🙏
